version: '3'

services:

  c-master:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-master-data:/var/lib/cassandra
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M
    networks:
      c-net:
        ipv4_address: 192.168.100.50

  c-node-1:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-node-1-data:/var/lib/cassandra
    depends_on:
      - c-master
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M
    networks:
      c-net:
        ipv4_address: 192.168.100.51

  c-node-2:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-node-2-data:/var/lib/cassandra
    depends_on:
      - c-master
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M
    networks:
      c-net:
        ipv4_address: 192.168.100.52

volumes:
  c-master-data:
  c-node-1-data:
  c-node-2-data:

networks:
  c-net:
    driver: macvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1