version: '3'

services:

  c-master:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-master-data:/var/lib/cassandra
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M
    networks:
      c-net:
        ipv4_address: <c_master_ip>

  c-node-1:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-node-1-data:/var/lib/cassandra
    depends_on:
      - c-master
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M
    networks:
      c-net:
        ipv4_address: <c_node_1_ip>

  c-node-2:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-node-2-data:/var/lib/cassandra
    depends_on:
      - c-master
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M
    networks:
      c-net:
        ipv4_address: <c_node_2_ip>

volumes:
  c-master-data:
  c-node-1-data:
  c-node-2-data:

networks:
  c-net:
    driver: macvlan
    driver_opts:
      parent: <host_network_dev>
    ipam:
      config:
        - subnet: <host_subnet>/<host_mask>
          gateway: <host_gateway>