version: '3'

services:

  c-master:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-master-data:/var/lib/cassandra
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M

  c-node-1:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-node-1-data:/var/lib/cassandra
    depends_on:
      - c-master
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M

  c-node-2:
    image: cassandra:4.0
    restart: unless-stopped
    environment:
      - CASSANDRA_SEEDS=c-master
      - CASSANDRA_CLUSTER_NAME=Cluster
    volumes:
      - c-node-2-data:/var/lib/cassandra
    depends_on:
      - c-master
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 866M

volumes:
  c-master-data:
  c-node-1-data:
  c-node-2-data:
